// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZUIf0i6sxrrfTm564u9vYBvXWedawOk',
    appId: '1:329046554723:web:b07306c141e15499bb2056',
    messagingSenderId: '329046554723',
    projectId: 'appli-gestion-cours',
    authDomain: 'appli-gestion-cours.firebaseapp.com',
    storageBucket: 'appli-gestion-cours.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgpwApJG1oPOB7F-5crUuEheGPAJZJeg',
    appId: '1:329046554723:android:1b2cc63a91de5d1ebb2056',
    messagingSenderId: '329046554723',
    projectId: 'appli-gestion-cours',
    storageBucket: 'appli-gestion-cours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kLU_UuwreQEl7IhIDTJkz5N4ys5LhJU',
    appId: '1:329046554723:ios:b2c109380387a502bb2056',
    messagingSenderId: '329046554723',
    projectId: 'appli-gestion-cours',
    storageBucket: 'appli-gestion-cours.firebasestorage.app',
    iosBundleId: 'com.example.gestionCoursApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kLU_UuwreQEl7IhIDTJkz5N4ys5LhJU',
    appId: '1:329046554723:ios:b2c109380387a502bb2056',
    messagingSenderId: '329046554723',
    projectId: 'appli-gestion-cours',
    storageBucket: 'appli-gestion-cours.firebasestorage.app',
    iosBundleId: 'com.example.gestionCoursApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIZUIf0i6sxrrfTm564u9vYBvXWedawOk',
    appId: '1:329046554723:web:e5d9ba9825d425aebb2056',
    messagingSenderId: '329046554723',
    projectId: 'appli-gestion-cours',
    authDomain: 'appli-gestion-cours.firebaseapp.com',
    storageBucket: 'appli-gestion-cours.firebasestorage.app',
  );
}
